### ISSUE TITLE
java.util.logging is left unbridged

### ISSUE THREAD

**Issue by codahale** [pyr/unilog#11]
Just came across a problem where a new library I added does all its logging via `java.util.logging` and was showing up independently in the logs. I had thought `unilog` added [the bridge](http://www.slf4j.org/api/org/slf4j/bridge/SLF4JBridgeHandler.html) itself, but it doesn’t. Would you be interested in a PR which adds that, or does that seem out of scope?

If you’re interested, would you want this to be default behavior (i.e. statically initialized), an optional function, or a config parameter?

**Comment by pyr** [comment]
Hi,

I'm hoping for unilog to give you a way to stop thinking about all the JVM logging options so definitely interested. Unless there's a big penalty for bringing the bridge by default, I think it'd be fine to have it on by default.

Thanks for looking into this.



On August 19, 2016 7:17:45 PM GMT+02:00, Coda Hale <notifications@github.com> wrote:
>Just came across a problem where a new library I added does all its
>logging via `java.util.logging` and was showing up independently in the
>logs. I had thought `unilog` added [the
>bridge](http://www.slf4j.org/api/org/slf4j/bridge/SLF4JBridgeHandler.html)
>itself, but it doesn’t. Would you be interested in a PR which adds
>that, or does that seem out of scope?
>
>If you’re interested, would you want this to be default behavior (i.e.
>statically initialized), an optional function, or a config parameter?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pyr/unilog/issues/11

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
