### ISSUE TITLE
Console logging verbosity

### ISSUE THREAD

**Issue by altvnk** [pyr/unilog#7]
If `:console` is set to `true` and verbosity is set to `:warn` i'm continuing to receive `DEBUG` messages in console output. Is there any way to configure that? I'm running `cyanite` in docker, so there is no need in file output, but output to console duplicates all the metrics and it's huge amount of duplicated data.

**Comment by crocket** [comment]
What was the configuration map passed to unilog?

**Comment by altvnk** [comment]
Here is config:
```yaml
logging:
  level: warn
  console: true
```

**Comment by crocket** [comment]
I tested the following code with unilog 0.7.8, and I didn't encounter the issue.

```clojure
(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (start-logging! {:level :warn
                   :console true})
  (loop [i 0]
    (Thread/sleep 500)
    (log/debug "oh, yes")
    (log/warn "okay")
    (recur (inc i))))
```

I think you should test unilog 0.7.8.

**Comment by altvnk** [comment]
Thank you, i will try.
